name: "Draft release when pushing new tag"

on:  # yamllint disable-line rule:truthy
  push:
    tags:
      - "v*"

jobs:
  pre-release:
    name: "Draft release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: "marvinpinto/action-automatic-releases@v1.2.0"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          draft: True
          prerelease: False
